#!/bin/bash
PYTHON=/cds/group/pcds/pyps/conda/py39/envs/pcds-5.9.1/bin/python
if [ ! -x "${PYTHON}" ]; then
    # Fallback for other filesystems, should be OK
    # Mostly for CI
    PYTHON=python3
fi
$PYTHON $0.py "$@"
